title: Harrison Goldstein
email: hgo@seas.upenn.edu
second-email: hgoldstein95@gmail.com
description: > #
  Harrison Goldstein has a masters degree in Computer Science from Cornell
  University. He is currently a PhD student at the University of Pennsylvania
  studying programming languages.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://harrisongoldste.in"
site_url: "https://harrisongoldste.in"
twitter_username: hgoldstein95
github_username: hgoldstein95

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
