title: Harrison Goldstein
email: hgoldstein95@gmail.com
description: > #
  Harrison Goldstein has a masters degree in Computer Science from Cornell
  University. He is currently a PhD student at the University of Pennsylvania
  studying programming languages.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://harrisongoldste.in"
site_url: "https://harrisongoldste.in"
twitter_username: hgoldstein95
github_username: hgoldstein95
profile_picture: img/profile.png

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

footer: yes
footer_url: "https://github.com/hgoldstein95/hgoldstein95.github.io"
footer_text: "Website source on GitHub"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Blog"
   link: "/blog"
#  - name: "About"
#    link: "/about/"
 - name: "CV"
   link: "/resume.pdf"

