title: Harrison Goldstein
email: me@harrisongoldste.in
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://harrisongoldste.in"
site_url: "https://harrisongoldste.in"
twitter_username: hgoldstein95
github_username: hgoldstein95
profile_picture: img/profile.jpeg

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

footer: yes
footer_url: "https://github.com/hgoldstein95/hgoldstein95.github.io"
footer_text: "Website source on GitHub"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Blog"
   link: "/blog"
 - name: "CV"
   link: "/resume.pdf"
 - name: "Contact"
   link: "#coordinates"

