title: Harrison Goldstein
email: hgoldstein95@gmail.com
description: > #
  Harrison Goldstein has a masters degree in Computer Science from Cornell
  University. He is currently a Software Engineer, and plans to pursue a PhD
  in programming languages.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://harrisongoldste.in" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: hgoldstein95
github_username: hgoldstein95

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
